from .boosting import adaboost
from .boosting import xgboost
from .lr import lr_regular
from .lr import lr_sgd
from .neighbors import knn
from .ensembles import random_forest
from .svm import svm_linear
from .svm import svm_rbf
from .utils import evaluate