defaults:
  - data: temporal
  - misc: conditional_trust
  - model: xgboost
  - rates: conditional_trust
hydra:
  run:
    dir: results/temp/trust_experiments/conditional/${now:%Y-%m-%d-%H-%M-%S}/
  output_subdir: .