# @package _global_
defaults:
  - data: temporal
  - misc: constant_trust
  - model: xgboost
  - rates: constant_trust
hydra:
  run:
    dir: results/temp/trust_experiments/constant/${now:%Y-%m-%d-%H-%M-%S}/
  output_subdir: .