# @package _global_
defaults:
  - data: temporal
  - misc: default
  - model: xgboost
  - rates: default
  - trust: default
  - optim: lr
  - update_params: feedback_full_fit
hydra:
  run:
    dir: results/temp/${now:%Y-%m-%d-%H-%M-%S}/
  output_subdir: .