# @package _group_
idr: fpr # Initial desired rate
idv: 0.2 # Initial desired rate
tvp: 0.2 # Threshold validation percentage
ddr: fpr # Dynamic desired rate
ddp: all # Dynamic desired partition
clinician_fpr: 0.0
clinician_trust: 1.0
train_lambda: 1.0