defaults:
  - regular: regular
  - lre: lre
#regular_momentum: 0.0
#regular_optimizer: SGD
#regular_weight_decay: 0.0
#lre_lr: 0.01
#lre_optimizer: SGD
#lre_momentum: 0.0
#lre_weight_decay: 0.0
#epochs: 2500
#early_stopping_iter: 20