type: nn_lre
regular:
  lr: 0.1
  momentum: 0.0
  nesterov: False
  optimizer: SGD
  weight_decay: 0.0
  epochs: 2500
  early_stopping_iter: 20
  log_tensorboard: False
lre:
  lr: 0.01
  momentum: 0.0
  nesterov: False
  optimizer: SGD
  weight_decay: 0.0
  epochs: 2500
  early_stopping_iter: 20
  val_proportion: 0.5
  incremental: False