type: nn_pu
lr: 0.1
momentum: 0.0
nesterov: False
optimizer: SGD
weight_decay: 0.0
epochs: 2500
early_stopping_iter: 20
gamma: 1.0
beta: 0.0
nnpu: False
log_tensorboard: False
combined_loss: False